### ISSUE TITLE
Unable to open AzeriteUI menu options

### ISSUE THREAD

**Issue by Aranzeb** [AzeriteTeam/AzeriteUI#24] opened 2019-06-29 20:36 UTC
## The problem  
 Right click to open ui menu option is not working.

### Make sure you can check all these boxes  
- [x] I have the latest addon version available from CurseForge/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [ ] Yes
- [x] No

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior

**Comment by goldpaw** [comment] 2019-06-30 08:37
Duplicate of #23, opened a few hours before this. Closing this and using the existing issue!

**Closed by goldpaw** 2019-06-30 08:37 UTC
Labels: bug
