### ISSUE TITLE
Health Preview texcoord out of range bug

### ISSUE THREAD

**Issue by AlexanderMlakar** [AzeriteTeam/AzeriteUI#17] opened 2019-04-23 14:53 UTC
## The problem  

The moment a player gets out of range in a battleground an LUI error pops. 

### Make sure you can check all these boxes  
- [x] I have the latest addon version available from CurseForge/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [x] Yes
- [ ] No

### What classes does it happen on?  

- [x] Death Knight 
- [x] Demon Hunter 
- [x] Druid 
- [x] Hunter 
- [x] Mage 
- [x] Monk 
- [x] Paladin 
- [x] Priest 
- [x] Rogue 
- [x] Shaman 
- [x] Warlock 
- [x] Warrior 

### Any logs, error output, etc?  

https://ghostbin.com/paste/s7j2w

### Steps to reproduce  

Queue a battleground and just fight with players. The moment they are out of range the error pops up.

**Comment by AlexanderMlakar** [comment] 2019-04-23 14:56
Hmm, maybe a typo: 'SetTexCoord'

**Comment by goldpaw** [comment] 2019-04-23 15:09
No typos in the code, that part wouldn't run at all if it was. 

Anyway, I've never encountered this bug myself in any groups, but I haven't done any battlegrounds in a long time so that might be why. I can see in the code where the problem is, though, so I'll get this fixed fairly fast here! :) 

The problem is that "preview" part of the health bar. It (meaning "me") forgets to check if the target is dead, and does all sort of crazy calculations ending up with texture coordinates with infinite numbers, thus causing the "TexCoord out of range" bug. Because texcoords have values ranging from 0 to 1, and "infinite" is definitely a little larger than that! 

Will get it fixed! :)

**Comment by AlexanderMlakar** [comment] 2019-04-23 15:31
Well that was fast :D

**Comment by goldpaw** [comment] 2019-04-24 13:43
Hopefully fixed in 1.2.141. I tried a BG, didn't get any bugs when anybody was out of range. Re-open this issue if it occurs again!

**Closed by goldpaw** 2019-04-24 13:43 UTC
Labels: bug
